eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761}/eureka
  
  instance:
      instanceId: ${DOMAIN_NAME:localhost}:${random.value}
      hostname: propets-auth-service
      nonSecurePort: ${PORT}

logging:
  pattern:
    dateformat: yyyy-MM-dd HH:mm:ss.SSS,Asia/Jerusalem
